Repository Alfresco/alfresco-process-sdk, pull requests merged in 2024-01, with the labels that each got.

#1001 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.106
  pom.xml
Labels: updatebot, develop

#1002 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.107
  pom.xml
Labels: updatebot, develop

#1003 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.89
  pom.xml
Labels: updatebot, develop

#1004 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.108
  pom.xml
Labels: updatebot, develop

#1005 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.63
  pom.xml
Labels: updatebot, develop

#1007 chore(deps): upgrade Activiti/activiti-cloud to version 8.2.0-alpha.26
  pom.xml
Labels: updatebot, develop

#1008 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.64
  pom.xml
Labels: updatebot, develop

#1009 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.91
  pom.xml
Labels: updatebot, develop

#1010 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.109
  pom.xml
Labels: updatebot, develop

#1012 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.92
  pom.xml
Labels: updatebot, develop

#1013 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.110
  pom.xml
Labels: updatebot, develop

#1014 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.65
  pom.xml
Labels: updatebot, develop

#1015 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.93
  pom.xml
Labels: updatebot, develop

#1016 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.111
  pom.xml
Labels: updatebot, develop

#1018 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.113
  pom.xml
Labels: updatebot, develop

#1019 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.114
  pom.xml
Labels: updatebot, develop

#1020 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.66
  pom.xml
Labels: updatebot, develop

#1021 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.115
  pom.xml
Labels: updatebot, develop

#1024 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.96
  pom.xml
Labels: updatebot, develop

#1025 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.116
  pom.xml
Labels: updatebot, develop

#1026 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.68
  pom.xml
Labels: updatebot, develop

#1027 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.97
  pom.xml
Labels: updatebot, develop

#1028 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.98
  pom.xml
Labels: updatebot, develop

#1029 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.118
  pom.xml
Labels: updatebot, develop

#1031 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.99
  pom.xml
Labels: updatebot, develop

#1032 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.119
  pom.xml
Labels: updatebot, develop

#1033 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.100
  pom.xml
Labels: updatebot, develop

#1036 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.101
  pom.xml
Labels: updatebot, develop

#1037 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.121
  pom.xml
Labels: updatebot, develop

#1038 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.122
  pom.xml
Labels: updatebot, develop

#1039 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.70
  pom.xml
Labels: updatebot, develop

#1040 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.102
  pom.xml
Labels: updatebot, develop

#1041 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.123
  pom.xml
Labels: updatebot, develop

#1042 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.72
  pom.xml
Labels: updatebot, develop

#1043 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.73
  pom.xml
Labels: updatebot, develop

#1044 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.104
  pom.xml
Labels: updatebot, develop

#1045 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.124
  pom.xml
Labels: updatebot, develop

#1046 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.74
  pom.xml
Labels: updatebot, develop

#1047 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.105
  pom.xml
Labels: updatebot, develop

#1048 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.125
  pom.xml
Labels: updatebot, develop

#1049 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.75
  pom.xml
Labels: updatebot, develop

#1050 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.106
  pom.xml
Labels: updatebot, develop

#1051 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.126
  pom.xml
Labels: updatebot, develop

#1052 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.107
  pom.xml
Labels: updatebot, develop

#1054 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.128
  pom.xml
Labels: updatebot, develop

#1055 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.108
  pom.xml
Labels: updatebot, develop

#1056 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.109
  pom.xml
Labels: updatebot, develop

#1057 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.129
  pom.xml
Labels: updatebot, develop

#1059 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.130
  pom.xml
Labels: updatebot, develop

#1060 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.131
  pom.xml
Labels: updatebot, develop

#1061 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.76
  pom.xml
Labels: updatebot, develop

#1062 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.110
  pom.xml
Labels: updatebot, develop

#1063 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.132
  pom.xml
Labels: updatebot, develop

#1064 chore(deps): upgrade Activiti/activiti-cloud to version 8.2.0-alpha.32
  pom.xml
Labels: updatebot, develop

#1065 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.133
  pom.xml
Labels: updatebot, develop

#1066 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.111
  pom.xml
Labels: updatebot, develop

#1067 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.134
  pom.xml
Labels: updatebot, develop

#1069 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.112
  pom.xml
Labels: updatebot, develop

#1070 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.135
  pom.xml
Labels: updatebot, develop

#1071 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.136
  pom.xml
Labels: updatebot, develop

#1072 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.137
  pom.xml
Labels: updatebot, develop

#1075 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.139
  pom.xml
Labels: updatebot, develop

#1076 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.140
  pom.xml
Labels: updatebot, develop

#1077 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.78
  pom.xml
Labels: updatebot, develop

#1078 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.114
  pom.xml
Labels: updatebot, develop

#1079 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.141
  pom.xml
Labels: updatebot, develop

#1080 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.79
  pom.xml
Labels: updatebot, develop

#1081 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.115
  pom.xml
Labels: updatebot, develop

#1083 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.142
  pom.xml
Labels: updatebot, develop

#1084 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.116
  pom.xml
Labels: updatebot, develop

#1085 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.143
  pom.xml
Labels: updatebot, develop

#1086 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.80
  pom.xml
Labels: updatebot, develop

#1087 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.117
  pom.xml
Labels: updatebot, develop

#1088 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.145
  pom.xml
Labels: updatebot, develop

#1089 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.81
  pom.xml
Labels: updatebot, develop

#1090 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.147
  pom.xml
Labels: updatebot, develop

#1093 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.148
  pom.xml
Labels: updatebot, develop

#1095 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.82
  pom.xml
Labels: updatebot, develop

#1097 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.119
  pom.xml
Labels: updatebot, develop

#1098 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.149
  pom.xml
Labels: updatebot, develop

#1100 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.150
  pom.xml
Labels: updatebot, develop

#1101 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.83
  pom.xml
Labels: updatebot, develop

#1102 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.120
  pom.xml
Labels: updatebot, develop

#1103 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.151
  pom.xml
Labels: updatebot, develop

#1104 chore(deps): upgrade Activiti/activiti-cloud to version 8.2.0-alpha.34
  pom.xml
Labels: updatebot, develop

#1105 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.84
  pom.xml
Labels: updatebot, develop

#1109 chore(deps): upgrade Activiti/activiti-cloud to version 8.2.0-alpha.35
  pom.xml
Labels: updatebot, develop

#1110 chore(deps): upgrade Alfresco/alfresco-process to version 7.14.0-alpha.85
  pom.xml
Labels: updatebot, develop

#1111 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.122
  pom.xml
Labels: updatebot, develop

#1112 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.153
  pom.xml
Labels: updatebot, develop

#1113 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.14.0-alpha.123
  pom.xml
Labels: updatebot, develop

#1114 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.14.0-alpha.154
  pom.xml
Labels: updatebot, develop

#1119 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.1
  pom.xml
Labels: updatebot, develop

#1120 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.1
  pom.xml
Labels: updatebot, develop

#1121 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.2
  pom.xml
Labels: updatebot, develop

#1122 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.2
  pom.xml
Labels: updatebot, develop

#1123 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.3
  pom.xml
Labels: updatebot, develop

#1124 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.4
  pom.xml
Labels: updatebot, develop

#1125 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.2
  pom.xml
Labels: updatebot, develop

#1126 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.3
  pom.xml
Labels: updatebot, develop

#1127 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.4
  pom.xml
Labels: updatebot, develop

#1128 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.5
  pom.xml
Labels: updatebot, develop

#1130 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.6
  pom.xml
Labels: updatebot, develop

#1131 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.7
  pom.xml
Labels: updatebot, develop

#1132 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.6
  pom.xml
Labels: updatebot, develop

#1099 AAE-19588 Upgrade Java Process SDK to Spring Boot 3.2.1
  pom.xml
Labels: dependencies, preview

#1133 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.7
  pom.xml
Labels: updatebot, develop

#1135 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.8
  pom.xml
Labels: updatebot, develop

#1136 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.4
  pom.xml
Labels: updatebot, develop

#1137 chore(deps): upgrade Activiti/activiti-cloud to version 8.3.0-alpha.2
  pom.xml
Labels: updatebot, develop

#1138 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.9
  pom.xml
Labels: updatebot, develop

#1139 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.9
  pom.xml
Labels: updatebot, develop

#1140 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.10
  pom.xml
Labels: updatebot, develop

#1141 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.5
  pom.xml
Labels: updatebot, develop

#1142 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.10
  pom.xml
Labels: updatebot, develop

#1144 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.11
  pom.xml
Labels: updatebot, develop

#1145 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.12
  pom.xml
Labels: updatebot, develop

#1146 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.12
  pom.xml
Labels: updatebot, develop

#1147 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.13
  pom.xml
Labels: updatebot, develop

#1148 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.14
  pom.xml
Labels: updatebot, develop

#1149 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.15
  pom.xml
Labels: updatebot, develop

#1150 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.16
  pom.xml
Labels: updatebot, develop

#1151 chore(deps): upgrade Activiti/activiti-cloud to version 8.3.0-alpha.3
  pom.xml
Labels: updatebot, develop

#1152 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.6
  pom.xml
Labels: updatebot, develop

#1153 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.13
  pom.xml
Labels: updatebot, develop

#1154 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.17
  pom.xml
Labels: updatebot, develop

#1155 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.14
  pom.xml
Labels: updatebot, develop

#1156 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.15
  pom.xml
Labels: updatebot, develop

#1157 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.18
  pom.xml
Labels: updatebot, develop

#1158 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.19
  pom.xml
Labels: updatebot, develop

#1161 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.16
  pom.xml
Labels: updatebot, develop

#1162 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.20
  pom.xml
Labels: updatebot, develop

#1164 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.7
  pom.xml
Labels: updatebot, develop

#1165 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.17
  pom.xml
Labels: updatebot, develop

#1166 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.22
  pom.xml
Labels: updatebot, develop

#1167 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.18
  pom.xml
Labels: updatebot, develop

#1168 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.23
  pom.xml
Labels: updatebot, develop

#1169 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.24
  pom.xml
Labels: updatebot, develop

#1170 chore(deps): upgrade Alfresco/alfresco-process to version 7.15.0-alpha.8
  pom.xml
Labels: updatebot, develop

#1171 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.19
  pom.xml
Labels: updatebot, develop

#1172 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.25
  pom.xml
Labels: updatebot, develop

#1173 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.26
  pom.xml
Labels: updatebot, develop

#1175 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.21
  pom.xml
Labels: updatebot, develop

#1176 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.22
  pom.xml
Labels: updatebot, develop, be-propagation

#1179 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.24
  pom.xml
Labels: updatebot, develop, be-propagation

#1180 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.25
  pom.xml
Labels: updatebot, develop, be-propagation

#1182 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.29
  pom.xml
Labels: updatebot, develop, be-propagation

#1183 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.30
  pom.xml
Labels: updatebot, develop, be-propagation

#1184 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.15.0-alpha.26
  pom.xml
Labels: updatebot, develop, be-propagation

#1185 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.15.0-alpha.31
  pom.xml
Labels: updatebot, develop, be-propagation
